# Generated by Django 4.1.1 on 2022-10-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя пользователя', max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=20, verbose_name='Ник')),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Пользователь', 'member'), ('Админ', 'admin'), ('Модератор', 'moderator')], default='member', max_length=12)),
                ('age', models.PositiveIntegerField()),
                ('location_id', models.ManyToManyField(to='ads.location')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.user'),
        ),
    ]
